### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by dbu** [php-http/utils#1]
@sagikazarmark said he thinks about changing the namespace to Utility

i think Util or Utils is good. we then should adjust the repository name to the name we settle on.

my vote goes for Utils

**Comment by sagikazarmark** [comment]
It doesn't matter, Utils is as good as Utility. Go ahead with it.

**Comment by dbu** [comment]
cool. is it ok if i:
- rename the namespace to `Utils`
- rename the composer name to `php-http/utils`
- rename this repository to `utils`

**Comment by sagikazarmark** [comment]
:+1:

**Comment by Nyholm** [comment]
:+1:
