### ISSUE TITLE
User and implementor stuff separation

### ISSUE THREAD

**Issue by dbu** [php-http/utils#13]
We discussed the role of php-http/utils versus php-http/helper. One idea was to separate things that HTTP client _users_ would need versus HTTP client _providers_. 

BatchRequest and BatchResponse are only relevant for implementors, not for users of a client. The users have to use the BatchResponse interface, and the BatchRequest trait is only relevant for adapters for non-parallel clients. Imho we should move those to helper (and maybe think of a better name for that repository, like client-implementation-helper)

**Comment by sagikazarmark** [comment]
Yeah, probably this point of view makes the most sense. Even if the logic of package organization might not be clear for everyone at first, it is easy to understand, so let's follow this.

Client-helper maybe?

**Comment by joelwurtz** [comment]
More than implementation-helper or integration-helper (like the adapter-integration-test package name)

(Client helper is confusing IMO)

**Comment by joelwurtz** [comment]
It can be closed i think, as all classes here now are user utilities.

**Comment by dbu** [comment]
right, thanks!

**Comment by sagikazarmark** [comment]
Reopening this as I think there is room for some more separation here. PR is on the way, after that we can decide about any further separation.

**Comment by dbu** [comment]
i think the Batch stuff we talked about is now fine here in utils, as there is no more interface. but if there are other implementor-only things i agree to separate them.

**Comment by sagikazarmark** [comment]
Yeah, that's why I changed the title.

I think that partly the Fulfilled/Rejected Promise thing can also be partly implementor things, but I am in the middle of planning.

In the meantime: naming question is still open. Utils? How should we call the two packages?

**Comment by dbu** [comment]
i think utils is a good name for user utilities. the other could be
implementor-tools maybe?

**Comment by sagikazarmark** [comment]
From the purpose of point of view, it is a good name.

From a domain point of view, it is not really.

**Comment by sagikazarmark** [comment]
Pushed changes in the [implementation_separation](https://github.com/php-http/utils/tree/implementation_separation) branch.

I would use these tools for example in the guzzle6 adapter where the sync behavior is currently emulated.

**Comment by dbu** [comment]
> From the purpose of point of view, it is a good name.
> 
> From a domain point of view, it is not really.

which one? utils? i would stick with utils as purpose is more relevant
here than domain - its a collection of stuff really...

for the implementor tools, i am open for better ideas, just tried to
come up with a name :-)

**Comment by sagikazarmark** [comment]
> which one? utils?

It is ok.

> for the implementor tools

Yeah, this one. I would drop the implementor part if possible. tools? httplug-tools? client-tools? integration-tools as @joelwurtz suggested?

I don't think we will find a name which describes the package correctly, so we definitely need to describe it anyway.

**Comment by dbu** [comment]
client-tools seems not bad. it goes well with the virtual client-implementation package

**Comment by sagikazarmark** [comment]
Solved in #20
