### ISSUE TITLE
Remove Body or include in HttpMethodsClient

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/utils#3]
Originally we wanted to remove Body implementations. Now, that HttpMethodsClient is an actual implementation and not an interface, we should reconsider keeping bodies and using them in the MethodsClient.

**Comment by dbu** [comment]
ah, i meant to ask about that. if you think it would be convenient, lets
re-allow Body in the HttpMethodsClient. but it would mean that the
protected send() method needs to handle the body, as the message factory
does not know about it.

**Comment by sagikazarmark** [comment]
Since they are in the same repo, I don't think it's a problem to implement some logic in the send method.

To tell the truth, it is very unlikely that I am going to use that feature. But I think they could be useful in some cases.

**Comment by dbu** [comment]
if you want to work on it, do it. otherwise we should remove the class
for now and only re-add it when its used somewhere.

**Comment by sagikazarmark** [comment]
The class? Body is not one class, but an interface and a set of classes. Go ahead and remove it for now.

**Comment by joelwurtz** [comment]
This can be close with #6
