### ISSUE TITLE
Helpers

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/utils#4]
Currently we also have a helper library:
https://github.com/php-http/helper

It contains some static helper classes migrated from ivory.
- Should we move them to the utility repo?
- Should we make them instantiable objects instead of the static usage?

**Comment by joelwurtz** [comment]
+1 For the utility repo and why not provide them as trait ?

**Comment by sagikazarmark** [comment]
I've already seen this kind of usage of traits (adding helper methods to classes), but I always had various feelings. Basically code is limited to be used as class methods this way. Also, by making them traits, they are "copied" to each place of usage. From the other hand, this is how multiple inheritance should work, apart from the copy thing.

**Comment by dbu** [comment]
looking at them, i feel most of them are about the request/response implementations and not about php-http. parsing the status code and similar things is not our job. everything that is handled by the Request / Response objects, we should drop from here.

for things that make sense to have, +1 for moving it to the utils repository and not have helpers. (also, "helpers" is a very unspecific name, as is "utils". one of those should be enough :-)
i am -1 on both static methods and traits. as with discovery, these things should be injected and only hardcoded as a last resort. that gives more flexibility and better separation of concerns. but lets see about that part when we identified which "helpers" we need at all.

**Comment by sagikazarmark** [comment]
I think helpers fit in PHP HTTP concept: they are PHP and HTTP. They are probably not closely related to httplug itself though, so keeping them separated might make sense. Utility is rather a collection of tools related to httplug.

Yeah, I would also be happier without traits and static.

**Comment by dbu** [comment]
> I think helpers fit in PHP HTTP concept: they are PHP and HTTP. They are
> probably not closely related to httplug itself though, so keeping them
> separated might make sense. Utility is rather a collection of tools
> related to httplug.

are the ivory helpers used anywhere? if so, we could offer the people
that use them to port them to php-http/helpers. just having this for the
sake of having seems of little value to me, and just adds stuff that
people need to figure out whether they need it or not. if i see it
correctly, the helpers are only relevant when you implement your own
Response class. imho we should focus on _using_ PSR7, not _implementing_
PSR7.

**Comment by sagikazarmark** [comment]
I would say we should decide whether they should be part of utility or not. (I vote for the latter). I agree that httplug is our first priority now, so we can think about the future of helpers later.

**Comment by dbu** [comment]
imho _utils_ should be utilities for _consumers_ of php-http.

with this logic, these helpers seem to not fit into utils as they are
for _implementors_ of PSR-7.

lets update the README of the helpers repo to clarify what they are and
are not.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by dbu** [comment]
created https://github.com/php-http/helper/pull/2

**Comment by sagikazarmark** [comment]
:+1:
